demo.settings:
  type: mapping
  label: Settings
  mapping:
    demo_dump_path:
      type: string
    demo_reset_last:
      type: integer
    demo_reset_interval:
      type: integer
    demo_dump_cron:
      type: string
